<a href="https://colab.research.google.com/github/chaehchaeh/MajorAI-MLTheory-Math-/blob/main/%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5%EC%9B%90%EB%A6%AC1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **<학습주제: preprocessing>**

scikit-learn: 기계학습을 위한 파이썬 라이브러리

###사이킷런 이용절차


1.   적절한 모형추정 클래스를 사이킷런으로부터 import한다
2.   모형추정 클래스에 필요한 하이퍼파라미터(초모수)들의 값을 부여하여 클래스를 객체화한다.
3. 2D텐서 x변수와 y변수를 정의한다
4. fit() 함수를 이용하여 학습데이터에 모형을 적합시킨다. 필요시 검증데이터에 적합한 모형을 적용하여 초모수를 조절한다.
5. 시험데이터에 predict() 또는  transform()함수를 이용하여 적합한 모형을 적용한다.




###사이킷런 변수의 종류
> feature(특성)변수: 독립변수, 외생변수, x변수 형태의 2D텐서

> target(목적)변수: 종속변수, 내생변수, y변수 형태의 2D텐서

ex) 특성변수가 5개인 표본 1개 x1=[[1,2,3,4,5]]

특성변수가 1개인 표본 5개 x2=[[1],[2],[3],[4],[5]]



## 실수 자료로의 전환(vectorization)

In [6]:
# 범주형 자료
x=[{'city':'seoul','temp':10.0},
   {'city':'Dubai','temp':33.5},
   {'city':'LA','temp':20.0}]
x

[{'city': 'seoul', 'temp': 10.0},
 {'city': 'Dubai', 'temp': 33.5},
 {'city': 'LA', 'temp': 20.0}]

In [ ]:
from sklearn.feature_extraction import DictVectorizer
vec=DictVectorizer(sparse=False) 
vec.fit_transform(x) #X를 범주형 수량화 자료로 변환 

array([[ 0. ,  0. ,  1. , 10. ],
       [ 1. ,  0. ,  0. , 33.5],
       [ 0. ,  1. ,  0. , 20. ]])

sparse=true는 원소0을 제외하고 표기함
sparse=True를 사용하면 메모리 용량을 줄일 수 있다.

In [7]:
from sklearn.feature_extraction import DictVectorizer
vec1=DictVectorizer(sparse=True)
x1=vec1.fit_transform(x)#X를 범주형 수량화 자료로 변환 
print(x1)

  (0, 2)	1.0
  (0, 3)	10.0
  (1, 0)	1.0
  (1, 3)	33.5
  (2, 1)	1.0
  (2, 3)	20.0


In [9]:
x2=x1.toarray()#sparse=True를 풀고 배열로 변경
print(x1)
print(x2)
vec1.get_feature_names_out()

  (0, 2)	1.0
  (0, 3)	10.0
  (1, 0)	1.0
  (1, 3)	33.5
  (2, 1)	1.0
  (2, 3)	20.0
[[ 0.   0.   1.  10. ]
 [ 1.   0.   0.  33.5]
 [ 0.   1.   0.  20. ]]


array(['city=Dubai', 'city=LA', 'city=seoul', 'temp'], dtype=object)

In [11]:
##가설: 여기 도시가 네개라면 1by4의 벡터로 표현될까
y=[{'city':'seoul','temp':10.0},
   {'city':'Dubai','temp':33.5},
   {'city':'LA','temp':20.0},
   {'city':'daugu','temp':15.0}]
y

[{'city': 'seoul', 'temp': 10.0},
 {'city': 'Dubai', 'temp': 33.5},
 {'city': 'LA', 'temp': 20.0},
 {'city': 'daugu', 'temp': 15.0}]

In [14]:
from sklearn.feature_extraction import DictVectorizer
vec=DictVectorizer(sparse=False)
vec.fit_transform(y)

array([[ 0. ,  0. ,  0. ,  1. , 10. ],
       [ 1. ,  0. ,  0. ,  0. , 33.5],
       [ 0. ,  1. ,  0. ,  0. , 20. ],
       [ 0. ,  0. ,  1. ,  0. , 15. ]])

In [16]:
#메모리를 줄이기 위해 sparse=True
vec1=DictVectorizer(sparse=True)
y1=vec1.fit_transform(y)
print(y1)

  (0, 3)	1.0
  (0, 4)	10.0
  (1, 0)	1.0
  (1, 4)	33.5
  (2, 1)	1.0
  (2, 4)	20.0
  (3, 2)	1.0
  (3, 4)	15.0


## *텍스트자료 수량화


In [18]:
#텍스트 자료
text=['떴다 떴다 비행기 날아라 날아라',
      '높이 높이 날아라 우리 비행기',
      '내가 만든 비행기 날아라 날아라',
      '멀리 멀리 날아라 우리 비행기']
text

['떴다 떴다 비행기 날아라 날아라',
 '높이 높이 날아라 우리 비행기',
 '내가 만든 비행기 날아라 날아라',
 '멀리 멀리 날아라 우리 비행기']

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
vec2=CountVectorizer() #default는 sparse=True
#Sparse=True를 풀고 텍스트를 수량화 배열 자료로 변환
t=vec2.fit_transform(text).toarray()
t

array([[2, 0, 0, 2, 0, 0, 1, 0],
       [1, 0, 2, 0, 0, 0, 1, 1],
       [2, 1, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 2, 1, 1]])

In [ ]:
import pandas as pd
t1=pd.DataFrame(t,columns=vec2.get_feature_names_out())
t1

날아라  내가  높이  떴다  만든  멀리  비행기  우리
0    2   0   0   2   0   0    1   0
1    1   0   2   0   0   0    1   1
2    2   1   0   0   1   0    1   0
3    1   0   0   0   0   2    1   1

###Term Frequency Inverse Document Frequency(TFIDF): 
출현 비중이 높은 단어에는 상대적으로 낮은 가중치를 주고 반대로 출현 비중이 낮은 단어에는 높은 가중치를 부여하는 방식

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid=TfidfVectorizer()
#높은 빈도는 낮은 가중치, 낮은 빈도는 높은 가중치
x2=tfid.fit_transform(text).toarray()
x3=pd.DataFrame(x2,columns=tfid.get_feature_names_out())
x3

날아라        내가       높이       떴다        만든       멀리       비행기        우리
0  0.450735  0.000000  0.00000  0.86374  0.000000  0.00000  0.225368  0.000000
1  0.229589  0.000000  0.87992  0.00000  0.000000  0.00000  0.229589  0.346869
2  0.569241  0.545415  0.00000  0.00000  0.545415  0.00000  0.284620  0.000000
3  0.229589  0.000000  0.00000  0.00000  0.000000  0.87992  0.229589  0.346869

###데이터척도(scale)에 의한 의존성을 제거하기 위한 방법
> 표준화: x_std=(x-mean(x))/sd(x) 

=편차/표준편차?

* mean(x): x의 평균
* sd(x): x의 표준편차

>정규화: x_nor= (x-min(x))/(max(x)-min(x))

=편차를 최댓값-최솟값으로 나눈 것?

##다항함수 회귀(Polynomial regression)

###1차 다항함수에 의한 회귀

In [2]:
 #폴리노미얼 특성변수 생성
 import plotly.express as px
 import numpy as np
 X=np.array([1,2,3,4,5])
 Y=np.array([5,3,1,5,8])
 fig=px.line(x=X,y=Y)#선형회귀를 하기에는 부적합
 fig.update_layout(width=500,height=380)
 fig.show()

###3차 다항함수에 의한 회귀

In [3]:
from sklearn.preprocessing import PolynomialFeatures
#include_bias는 절편항 여부
fg=PolynomialFeatures(degree=3,include_bias=True)
x1=fg.fit_transform(X[:,np.newaxis])#3차까지 생성
print(x1)

[[  1.   1.   1.   1.]
 [  1.   2.   4.   8.]
 [  1.   3.   9.  27.]
 [  1.   4.  16.  64.]
 [  1.   5.  25. 125.]]


In [4]:
from sklearn.linear_model import LinearRegression
import plotly.graph_objects as go
reg=LinearRegression()
reg.fit(x1,Y)
yfit=reg.predict(x1) #적합값
fig=go.Figure()
fig.add_trace(go.Scatter(x=X,y=Y,mode='lines',name='origin'))
fig.add_trace(go.Scatter(x=X,y=yfit,mode='lines+markers',name='fitted'))
fig.show()