<a href="https://colab.research.google.com/github/chaehchaeh/MajorAI-MLTheory-Math-/blob/main/%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5%EC%9B%90%EB%A6%AC1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 실수 자료로의 전환(vectorization)

In [ ]:
# 범주형 자료
x=[{'city':'seoul','temp':10.0},
   {'city':'Dubai','temp':33.5},
   {'city':'LA','temp':20.0}]
x

[{'city': 'seoul', 'temp': 10.0},
 {'city': 'Dubai', 'temp': 33.5},
 {'city': 'LA', 'temp': 20.0}]

In [ ]:
from sklearn.feature_extraction import DictVectorizer
vec=DictVectorizer(sparse=False) 
vec.fit_transform(x) #X를 범주형 수량화 자료로 변환 

array([[ 0. ,  0. ,  1. , 10. ],
       [ 1. ,  0. ,  0. , 33.5],
       [ 0. ,  1. ,  0. , 20. ]])

In [ ]:
##가설: 여기 도시가 네개라면 1by4의 벡터로 표현될까
y=[{'city':'seoul','temp':10.0},
   {'city':'Dubai','temp':33.5},
   {'city':'LA','temp':20.0},
   {'city':'daugu','temp':15.0}]
y

[{'city': 'seoul', 'temp': 10.0},
 {'city': 'Dubai', 'temp': 33.5},
 {'city': 'LA', 'temp': 20.0},
 {'city': 'daugu', 'temp': 15.0}]

In [ ]:
vec.fit_transform(y)

array([[ 0. ,  0. ,  0. ,  1. , 10. ],
       [ 1. ,  0. ,  0. ,  0. , 33.5],
       [ 0. ,  1. ,  0. ,  0. , 20. ],
       [ 0. ,  0. ,  1. ,  0. , 15. ]])

In [ ]:
#메모리를 줄이기 위해 sparse=True
vec1=DictVectorizer(sparse=True)
x1=vec1.fit_transform(x)
x1

<3x4 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [ ]:
x2=x1.toarray() #sparse=True를 풀고 배열로 변경
print(x1)
print(x2)
vec1.get_feature_names_out()

  (0, 2)	1.0
  (0, 3)	10.0
  (1, 0)	1.0
  (1, 3)	33.5
  (2, 1)	1.0
  (2, 3)	20.0
[[ 0.   0.   1.  10. ]
 [ 1.   0.   0.  33.5]
 [ 0.   1.   0.  20. ]]


array(['city=Dubai', 'city=LA', 'city=seoul', 'temp'], dtype=object)